export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ProductDetailPage } from './ProductDetailPage'
export { HomePage } from './HomePage'
export { ProductsPage } from './ProductsPage'
